fix: wrap EventCard title text
jabbate19/rideboard-v2 pull request #9
Opened 2024-11-09 21:42 UTC by costowell

2025-03-23 00:09 UTC, jabbate19 commented
@costowell can we fix this UI bug on mobile? 
<img width="526" alt="image" src="https://github.com/user-attachments/assets/9b82e44c-34f3-46cc-b19c-53c60af6316a" />

2025-03-23 00:10 UTC, jabbate19 requested changes
You may need to remove `noOverflow` from the card as well for this to work. Please provide screenshots from mobile and laptop sizes to verify!

2025-03-23 17:27 UTC, costowell commented
I can't seem to reproduce this on my end.

2025-05-03 18:13 UTC, jabbate19 commented
<img width="425" alt="image" src="https://github.com/user-attachments/assets/4c23f512-9f8b-4ce1-892d-2f5aab2bb7fe" />
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/c1ff85c7-02bf-4d93-994e-d3bb4b7b109f" />
Merged against main. Scroll still occurs for long title and location in event-detail card

2026-06-05 18:49 UTC, closed without merging